require 'ssh_scan/error/connect_timeout'
require 'ssh_scan/error/closed_connection'
require 'ssh_scan/error/connection_refused'
require 'ssh_scan/error/disconnected'
require 'ssh_scan/error/no_banner'
require 'ssh_scan/error/no_kex_response'
