name: 'Setup Ruby, JRuby and TruffleRuby'
description: 'Download a prebuilt Ruby and add it to the PATH in 5 seconds'
author: 'Benoit Daloze'
branding:
  color: red
  icon: download
inputs:
  ruby-version:
    description: 'Engine and version to use, see the syntax in the README. Reads from .ruby-version or .tool-versions if unset.'
    required: false
    default: 'default'
  bundler:
    description: |
      The version of Bundler to install. Either 'none', 'latest', 'Gemfile.lock', or a version number (e.g., 1, 2, 2.1.4).
      For 'Gemfile.lock', the version is determined based on the BUNDLED WITH section from the file Gemfile.lock, $BUNDLE_GEMFILE.lock or gems.locked.
      Defaults to 'Gemfile.lock' if the file exists and 'latest' otherwise.
    required: false
    default: 'default'
  bundler-cache:
    description: 'Run "bundle install", and cache the result automatically. Either true or false.'
    required: false
    default: 'false'
  working-directory:
    description: 'The working directory to use for resolving paths for .ruby-version, .tool-versions and Gemfile.lock.'
    required: false
    default: '.'
  cache-version:
    description: |
      Arbitrary string that will be added to the cache key of the bundler cache. Set or change it if you need
      to invalidate the cache.
    required: false
    default: '0'
outputs:
  ruby-prefix:
    description: 'The prefix of the installed ruby'
runs:
  using: 'node12'
  main: 'dist/index.js'
